ibkr:
  ibGateway:
    image:
      repository: ghcr.io/extrange/ibkr
      tag: "10.37"
      pullPolicy: IfNotPresent

  mcpAuth:
    create: false
    existingSecret: ibkr-credentials

  gatewaySecret:
    existingSecret: ibkr-credentials

  mcpServer:
    image:
      repository: ghcr.io/omdv/ibkr-mcp-server
      tag: "0.1.20"
      pullPolicy: IfNotPresent
    ingress:
      enabled: true
      className: nginx
      host: ibkr.kblb.io
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        hajimari.io/enable: "true"
        hajimari.io/icon: "chart-line"
        hajimari.io/appName: "ibkr-api"
      tls:
        - secretName: ibkr-mcp-server-tls
          hosts:
            - ibkr.kblb.io

  config:
    enableMcp: "false"
    ibkrLogLevel: "INFO"
