---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kanboard
  labels:
    app: kanboard
    gethomepage.dev/enabled: "true"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.middlewares: traefik-oauth2-proxy-chain@kubernetescrd
    hajimari.io/enable: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - kanboard.kblb.io
      secretName: my-certs-kanboard
  rules:
    - host: kanboard.kblb.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanboard
                port:
                  name: http
