---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: kolmafia
  labels:
    app: kolmafia

spec:
  replicas: 1
  selector:
    matchLabels:
      app: kolmafia
  template:
    metadata:
      labels:
        app: kolmafia
    spec:
      initContainers:
        - name: volume-owner
          image: busybox:1.37.0
          command: ["sh", "-c", "chown -R 1000:1000 /config/.kolmafia"]
          volumeMounts:
            - name: kolmafia-data
              mountPath: /config/.kolmafia
      containers:
        - name: kolmafia
          image: ghcr.io/loathers/kolmafia-docker:latest
          ports:
            - name: web
              protocol: TCP
              containerPort: 3000
            - name: relay
              protocol: TCP
              containerPort: 60080
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: VNC_PASSWORDLESS
              value: "true"
            - name: VNC_RESOLUTION
              value: "1600x900"
          volumeMounts:
            - name: kolmafia-data
              mountPath: /config/.kolmafia
      volumes:
        - name: kolmafia-data
          persistentVolumeClaim:
            claimName: pvc-kolmafia
