apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster
  - databases

patches:
  - path: databases/patch-managed-roles.yaml
    target:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster
      name: cnpg-cluster
