---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: cnpg-backblaze
spec:
  retentionPolicy: "30d"
  configuration:
    destinationPath: "s3://omdv-cnpg-backup/cnpg"
    endpointURL: "https://s3.us-west-001.backblazeb2.com"
    s3Credentials:
      accessKeyId:
        name: backblaze-s3-creds
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: backblaze-s3-creds
        key: ACCESS_SECRET_KEY
    wal:
      compression: gzip
      encryption: "AES256"
      maxParallel: 8
    data:
      compression: gzip
      encryption: "AES256"
      jobs: 2
