---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-errors
spec:
  errors:
    status:
      - "401-403"
    statusRewrites:
      "401": 302
    service:
      name: oauth2-proxy
      namespace: networking
      port: http
    query: "/oauth2/sign_in?rd={url}"

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-forward-auth
spec:
  forwardAuth:
    address: http://oauth2-proxy.networking.svc.cluster.local:4180/oauth2/auth
    trustForwardHeader: true
    authResponseHeaders:
      - X-Auth-Request-User
      - X-Auth-Request-Email
      - X-Auth-Request-Preferred-Username
      - X-Auth-Request-Groups
      - X-Auth-Request-Access-Token
      - Authorization

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-proxy-chain
spec:
  chain:
    middlewares:
      - name: oauth2-errors
      - name: oauth2-forward-auth

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-authorization
spec:
  headers:
    customRequestHeaders:
      Authorization: ""

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: oauth2-argocd-chain
spec:
  chain:
    middlewares:
      - name: oauth2-forward-auth
      - name: strip-authorization
