---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ibkr-credentials
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: ibkr-credentials
  data:
    - secretKey: authToken
      remoteRef:
        key: secret/ibkr
        property: VAULT_IBKR_AUTH_TOKEN
    - secretKey: username
      remoteRef:
        key: secret/ibkr
        property: VAULT_IBKR_USERNAME
    - secretKey: password
      remoteRef:
        key: secret/ibkr
        property: VAULT_IBKR_PASSWORD
