---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-deeptutor-data
  labels:
    app: deeptutor
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  local:
    path: /pool/knowledge
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/control-plane
              operator: Exists
