---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-deeptutor-data
  labels:
    app: deeptutor
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-deeptutor-data
