---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backblaze-s3-creds
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backblaze-s3-creds
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: secret/cnpg-backblaze
        property: VAULT_BACKBLAZE_ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: secret/cnpg-backblaze
        property: VAULT_BACKBLAZE_ACCESS_SECRET_KEY
