apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-cluster
spec:
  managed:
    roles:
      - name: paperless
        ensure: present
        login: true
        passwordSecret:
          name: paperless-db-user
