---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-atomic
  labels:
    app: atomic
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /pool/config/atomic

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-atomic
  labels:
    app: atomic
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeName: pv-atomic
